print("Welcome to the tip calculator!")
bill = int(input("What was the total bill? "))
tip = int(input("What percentage tip would you like to give? 10, 12 or even 15 "))
people = int(input("How many people want to split the bill? "))
final_bill = round(bill * (1 + (tip) / 100) / people, 2)
print(f"Each person should pay: ${final_bill}")
